### ISSUE TITLE
Possible error in chapter 4

### ISSUE THREAD

**Issue by zikalify** [standardebooks/jerome-k-jerome_three-men-in-a-boat#1]
Please do a ctrl+f for 'an hotel' in the link below. Should it be 'a hotel' or is it just the way the character is speaking?

https://github.com/standardebooks/jerome-k-jerome_three-men-in-a-boat/blob/master/src/epub/text/chapter-4.xhtml

**Comment by acabal** [comment]
It's likely the speech pattern, some British English accents don't pronounce leading H's.
